---

name: Build and Publish

on: push

jobs:

  ##==-- Build
  build:
    # on an Ubuntu VM, build inside a golang container
    runs-on: ubuntu-latest
    container: golang:1.16-buster

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: make test

      - name: Build
        shell: bash
        run: |
          set -euo pipefail
          export PATH=$PATH:$(go env GOPATH)/bin

          go get github.com/mitchellh/gox  # prereq
          make dev  # only produce the Linux AMD64 binary

      - name: Upload binary for later jobs
        uses: actions/upload-artifact@v2
        with:
          name: vault-plugin-secrets-active-directory
          path: bin/vault-plugin-secrets-active-directory

  ##==-- Publish
  publish:
    needs: build
    # on an Ubuntu VM, not within a container
    runs-on: ubuntu-latest

    steps:
      - name: Download binary from previous job
        uses: actions/download-artifact@v2
        with:
          name: vault-plugin-secrets-active-directory

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/reece-v')
        with:
          files: bin/vault-plugin-secrets-active-directory
